UOS25/UOS25/UOS25/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from mainapp.views import *
from django.conf.urls import url

# 본사 페이지
central_urlpatterns = [
    url(r'^central/$',indexAdmin, name='indexAdmin'),#본사인덱스
    url(r'^central/franchiseManage/$',franchiseManage, name='franchiseManage'),#가맹점 관리
    url(r'^central/franchiseCostManage/$',franchiseCostManage, name='franchiseCostManage'),#가맹요금 수납
    url(r'^central/supplierManage/$', supplierManage, name='supplierManage'),#납품 업체 관리
    url(r'^central/storeOrderManage/$', storeOrderManage, name='storeOrderManage'),#지점 주문 관리
    url(r'^central/storeOrderManage/list/$', storeOrderManageList, name='storeOrderManageList'),#지점 주문 관리
    url(r'^central/storeRefundManage/$', storeRefundManage, name='storeRefundManage'),#지점 반품 관리
    url(r'^central/productManage/$', productManage, name='productManage'),#상품 관리
    url(r'^central/productManage/product_pic/(?P<pic_number>\w+)/$', productPicture, name='productPicture'), #상품 사진 표시
    url(r'^central/customerManage/$',customerManage, name='customerManage'),#고객 관리
]

# 가맹점 페이지
franchise_urlpatterns = [    
    url(r'^franchise/$',index, name='index'),#가맹점인덱스
    url(r'^franchise/orderManage/$',orderManage, name='orderManage'),#주문관리
    url(r'^franchise/orderManage/list/$', orderManageList, name='orderManageList'), #주문목록확인
    url(r'^franchise/centralRefundManage/$', centralRefundManage, name='centralRefundManage'),#본사반품관리
    url(r'^franchise/saleProduct/$', saleProduct, name='saleProduct'),#물품판매
    url(r'^franchise/saleProduct/list/$', saleProductList, name='saleProductList'), #물품판매목록
    url(r'^franchise/customerRefundManage/$', customerRefundManage, name='customerRefundManage'),#고객반품관리
    url(r'^franchise/stockManage/$',stockManage, name='stockManage'),#재고관리
    url(r'^franchise/productManageStore/$', productManageStore, name='productManageStore'),#상품 관리
    url(r'^franchise/expireDateManage/$',expireDateManage, name='expireDateManage'),#유통기한관리
    url(r'^franchise/saleManage/$',saleManage, name='saleManage'),#매출관리
    url(r'^franchise/maintenanceCostManage/$',maintenanceCostManage, name='maintenanceCostManage'),#유지비관리
    url(r'^franchise/employeeManage/$',employeeManage, name='employeeManage'),#점원관리
    url(r'^franchise/workListManage/$',workListManage, name='workListManage'),#근무기록관리
    url(r'^franchise/salaryManage/$',salaryManage, name='salaryManage'),#월급관리
    url(r'^franchise/productManageStore/product_pic/(?P<pic_number>\w+)/$', productPicture, name='productPicture'), #상품 사진 표시
]

# 통합페이지
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login, name='login'),#로그인페이지
] + central_urlpatterns + franchise_urlpatterns

UOS25/UOS25/mainapp/models.py
from django.db import models, connection
from decimal import Decimal
from mainapp.sqls import SQLs

# Create your models here.

# 지점 테이블
class Store(models.Model):
    address = models.CharField(max_length=80, null=False)
    contact = models.CharField(max_length=20, null=False)
    # 용어사전 반영 필요
    store_pay = models.DecimalField(decimal_places=2, max_digits=3,null=False) # 가맹요금비율

    __STORE_CODE__ = [
        (1, '개점'),
        (2, '폐점'),
    ]
    store_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__STORE_CODE__, null=False) # 지점상태코드

    def __str__(self):
        return '_'.join((str(self.id), self.address[:10]))

# 납품업체 테이블
class Supplier(models.Model):
    name = models.CharField(max_length=25, null=False)
    contact = models.CharField(max_length=20, null=False)
    email = models.CharField(max_length=40, null=False)

    def __str__(self):
        return self.name
    
# 상품 테이블
class Product(models.Model):
    barcode = models.DecimalField(decimal_places=0, max_digits=13, primary_key=True)
    name = models.CharField(max_length=50, null=False)
    supply_price = models.DecimalField(decimal_places=0, max_digits=10, null=False)
    unit_price = models.DecimalField(decimal_places=0, max_digits=10, null=False)
    supplier_id = models.ForeignKey(Supplier, null=False, db_column='supplier_id')

    __CATEGORY_A__ = [
        (0, '기타'),
        (1, '신선식품'),
        (2, '식품'),
        (3, '주류'),
        (4, '생활용품'),
        (5, '담배')
    ]
    category_a = models.DecimalField(decimal_places=0, max_digits=4, choices=__CATEGORY_A__, null=False) # 상품 분류 코드

    __CATEGORY_B__ = [
        (0, '일반판매'),
        (1, '기간한정판매'),
        (2, '할인행사판매')
    ]
    category_b = models.DecimalField(decimal_places=0, max_digits=4, choices=__CATEGORY_B__, null=False) # 판매 분류 코드
    explain = models.CharField(max_length=80, null=True)
    picture_file_path = models.CharField(max_length=80, null=True) # 사진파일경로

    def __str__(self):
        return self.name

# 재고 테이블
class Stock(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    __DISP_LOC_CODE__ = [
        (0, '진열'),
        (1, '창고'),
        (2, '매장외부'),
    ]
    display_location_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__DISP_LOC_CODE__, null=False)
    barcode  = models.ForeignKey(Product, null=False, db_column='barcode')
    quantity = models.DecimalField(decimal_places=0, max_digits=6, default=0, null=False)

# 주문 테이블
class Order(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    order_timestamp = models.DateTimeField(null=False)
    complete_timestamp = models.DateTimeField(null=True)

    __PROCESS_CODE__ = [
        (0, '처리대기'),
        (1, '배송시작'),
        (2, '배송완료'),
        (3, '처리완료'),
        (-1, '주문취소'),
    ]
    process_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__PROCESS_CODE__, null=False)
    
    def sum_price(self):
        with connection.cursor() as cursor:
            gett = cursor.execute(SQLs.sql_storeOrderTotalPrice,[self.id]).fetchone() 
            val = gett[0]
        return val
        
    
# 주문내역 테이블
class Order_list(models.Model):
    barcode = models.ForeignKey(Product, null=False, db_column='barcode')
    quantity = models.DecimalField(decimal_places=0, max_digits=6, null=False)
    sent_timestamp = models.DateTimeField(null=True)
    arrival_timestamp = models.DateTimeField(null=True)

    __PROCESS_CODE__ = [
        (0, '처리대기'),
        (1, '배송시작'),
        (2, '배송완료'),
        (3, '처리완료'),
        (-1, '주문취소'),
        (-2, '처리불가'),
    ]
    process_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__PROCESS_CODE__, null=False)
    order_id = models.ForeignKey(Order, null=False, db_column='order_id') #기존 것은 db_column 빼먹었으므로 고친다면 주의

# 지점반품 테이블
class Store_refund(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    barcode = models.ForeignKey(Product, null=False, db_column='barcode')
    quantity = models.DecimalField(decimal_places=0, max_digits=6, null=False)
    refund_timestamp = models.DateTimeField(null=False)

    __REFUND_REASON_CODE__ = [
        (0, '일반반품'),
        (1, '본사리콜'),
        (2, '불량품'),
        (-1, '유통기한폐기')
    ]
    refund_reason_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__REFUND_REASON_CODE__, null=False)

    __PROCESS_CODE__ = [
        (0, '반품대기'),
        (1, '회수완료'),
        (2, '반품불가'),
        (-1, '자체폐기'),
    ]
    process_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__PROCESS_CODE__, null=False)

# 가맹요금수납 테이블
class Franchise_store_rcpt(models.Model): # 가맹요금수납
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    rcpt_date = models.DateField(null=False)
    rcpt_amount = models.DecimalField(decimal_places=0, max_digits=10, null=False)
    
# 점원 테이블
class Employee(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    name = models.CharField(max_length=25, null=False)
    daytime_hourpay = models.DecimalField(decimal_places=0, max_digits=10, null=True, default=6800)
    nighttime_hourpay = models.DecimalField(decimal_places=0, max_digits=10, null=True)
    employed_date =  models.DateField(null=False)
    fire_date=  models.DateField(null=True)
    contact = models.CharField(max_length=20, null=False)

    __POSITION_CODE__ = [
        (0, '점주'),
        (1, '매니저'),
        (2, '직원'),
    ]
    position_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__POSITION_CODE__, null=False)

    def __str__(self):
        return self.name

# 근무기록 테이블
class Work_list(models.Model):
    employee_id = models.ForeignKey(Employee, null=False, db_column='employee_id')
    workstart_timestamp = models.DateTimeField(null=False)
    workend_timestamp = models.DateTimeField(null=False)

    __STOREOWNER_CHECK__ = [
        ('N', '미확인'),
        ('Y', '확인'),
    ]
    storeowner_check = models.CharField(max_length=1, default='N', choices=__STOREOWNER_CHECK__, null=False)

# 유지비 테이블
class Maintenance_cost(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    __MAINTENANCE_COST_CODE__ = [
        (0, '기타'),
        (1, '세금/유지비'),
        (2, '월세'),
        (3, '직원과실'),
        (4, '절도')
    ]
    maintenance_cost_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__MAINTENANCE_COST_CODE__, null=False)
    amount = models.DecimalField(decimal_places=0, max_digits=10, null=False)
    process_date = models.DateField(null=False)
    employee_id = models.ForeignKey(Employee, null=True, db_column='employee_id')
    etc = models.CharField(max_length=80, null=True) # 비고
    __STOREOWNER_CHECK__ = [
        ('N', '미확인'),
        ('Y', '확인'),
    ]
    storeowner_check = models.CharField(max_length=1, default='N', choices=__STOREOWNER_CHECK__, null=False)
 
# 고객 테이블
class Customer(models.Model):
    name = models.CharField(max_length=25, null=False)
    mileage = models.DecimalField(decimal_places=0, max_digits=10, default=0, null=False)
    __GENDER__ = [
        (None, '미선택'),
        (1, '남'),
        (2, '여')
    ]
    gender = models.DecimalField(decimal_places=0, max_digits=4, choices=__GENDER__, null=True)
    birthday = models.DateField(null=True)
    contact = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name

# 영수증 테이블
class Receipt(models.Model):
    store_id = models.ForeignKey(Store, null=False, db_column='store_id')
    trade_timestamp = models.DateTimeField(null=False)
    employee_id = models.ForeignKey(Employee, null=False, db_column='employee_id')
    customer_id = models.ForeignKey(Customer, null=True, db_column='customer_id')
    __PAYMENT_METHOD_CODE__ = [
        (0, '현금'),
        (1, '체크/신용카드'),
        (2, '편의점상품권'),
        (3, '마일리지'),
        (4, '간편결제앱'),
    ]
    payment_method_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__PAYMENT_METHOD_CODE__, null=False)
    payment_information = models.CharField(max_length=30, null=True)
    
# 거래내역 테이블
class Trade_list(models.Model):
    receipt_id = models.ForeignKey(Receipt, null=False, db_column='receipt_id')
    barcode = models.ForeignKey(Product, null=False, db_column='barcode')
    quantity = models.DecimalField(decimal_places=0, max_digits=6, null=False)
    __IS_REFUND__ = [
        ('N', '미반품'),
        ('Y', '반품됨'),
    ]
    is_refund = models.CharField(max_length=1, default='N', null=False)

    def __str__(self):
        return "{}번_판매_{}_{}개".format(self.receipt_id.id, self.barcode, self.quantity)
    
# 고객반품 테이블
class Customer_refund(models.Model):
    trade_list_id = models.ForeignKey(Trade_list, null=False, db_column='trade_list_id')
    refund_timestamp = models.DateTimeField(null=False)
    __REFUND_REASON_CODE__ = [
        (0, '일반반품'),
        (1, '본사리콜'),
        (2, '불량품'),
        (-1, '유통기한')
    ]
    refund_reason_code = models.DecimalField(decimal_places=0, max_digits=4, choices=__REFUND_REASON_CODE__, null=False)

class Setting(models.Model):
    name = models.CharField(max_length=20)
    value = models.DecimalField(max_digits=10, decimal_places=0)

class Code(models.Model):
    information = models.CharField(max_length=20)

class User(models.Model):
    user_id = models.CharField(max_length=50)
    password = models.CharField(max_length=200)
    store_id = models.ForeignKey(Store, db_column='store_id', null=True)
    # employee_id = models.ForeignKey(Employee, db_column='employee_id', null=True)
    __EMP_POS_CODE__ = [
        (0, '지점장/본점장'),
        (1, '직원'),
    ]
    emp_pos_code = models.DecimalField(max_digits=1, decimal_places=0, choices=__EMP_POS_CODE__, null=False, default=0)

UOS25/UOS25/mainapp/templates/deleteProduct.html
{% extends 'base.html' %}
{% block content %}
<div class="panel panel-default" style="margin-bottom:0px">
  <div class="panel-body" style="margin-left:50px">
    <h1>재고삭제</h1>
  </div>
</div>
  <form method="POST" style="margin-left:50px; padding-top:50px; padding-bottom:50px">
    <div class="form-group">
      <label for="name">상품명</label>
      <input type="text" class="form-control" id="name" name="name" maxlength="50" style="width:auto">
    </div>
    {%csrf_token%}
    <button type="submit" class="btn btn-default">삭제하기</button>
  </form>
{%endblock%}

UOS25/UOS25/mainapp/templates/employeeManage.html
{% extends 'base.html' %}

{% load bootstrap3 %}
{% block calendar_widget %}
{{ employeeRegisterForm.media }}
{{ employeeUpdateForm.media }}
{% endblock %}

{% block content %}
<div class="panel panel-default" style="margin-bottom:0px">
  <div class="panel-body" style="margin-left:50px">
    <h1>점원 관리</h1>
  </div>
</div>
<table class="table table-striped" style="margin-left:5px">
  <thead>
    <tr>
      <th>이름</th>
      <th>주간 시급</th>
      <th>야간 시급</th>
      <th>고용일</th>
      <th>해고일</th>
      <th>연락처</th>
      <th>직급</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{ employee.name }}</td>
      <td>{{ employee.daytime_hourpay }}</td>
      <td>{{ employee.nighttime_hourpay }}</td>
      <td>{{ employee.employed_date }}</td>
      <td>{{ employee.fire_date | default_if_none:"" }}</td>
      <td>{{ employee.contact }}</td>
      <td>{{ employee.get_position_code_display }}</td>
      <td><button type="button" class="btn btn-success" data-toggle="modal" data-target="#update" 
        onclick="update_onclick({{ employee.id }}, '{{ employee.name }}', {{ employee.daytime_hourpay }}, {{ employee.nighttime_hourpay }},
        '{{ employee.employed_date }}', '{{employee.fire_date | default_if_none:""}}', '{{employee.contact}}', '{{employee.position_code}}')">수정</button></td>
      <td><button type="button" class="btn btn-success" data-toggle="modal" data-target="#del" 
        onclick="delete_onclick({{ employee.id }}, '{{employee.name}}')">삭제</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!--추가 버튼 및 페이지 표시 -->
<nav>
  <div class="text-center">
    <ul class="pagination">
      <li>
          <span aria-hidden="true">-</span>
      </li>
      {% for page in pages %}
      {% if this_page == page %}
      <li class="active"><a href="?page={{page}}">{{page}}</a></li>
      {% else %}
      <li><a href="?page={{page}}">{{page}}</a></li>
      {% endif %}
      {% endfor %}
      <li>
          <span aria-hidden="true">-</span>
      </li>
    </ul>
  </div>

  <!-- 추가 버튼 -->
  <div class="btn-group" role="group" style="margin-top:-100px;margin-left: 20px">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add">점원 추가</button>
  </div>

</nav>

<!--add모달-->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="addLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addLabel">점원 추가</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'employeeManage' %}?process=register&page={{this_page}}" method="POST">
      <div class="modal-body input-group">
        {% bootstrap_form employeeRegisterForm %}
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>
      </form>

    </div>
  </div>
</div>

<script type="text/javascript">
delete_onclick = function(id, name) {
  $("#delete_id").text(name);
  $("#del_id").val(id);
}
update_onclick = function(id, name, dpay, npay, edate, fdate, contact, poscode) {
  $("#update_id").val(id);
  $("#update_name").val(name);
  $("#update_daytime_hourpay").val(dpay);
  $("#update_nighttime_hourpay").val(npay);
  $("#update_employed_date").val(edate);
  $("#update_fire_date").val(fdate);
  $("#update_contact").val(contact);
  $("#update_position_code").val(poscode);
}
</script>

<!--del모달-->
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="delLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="delLabel">삭제하기</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'employeeManage' %}?process=delete&page={{this_page}}" method="POST">
      <div class="modal-body">
        <span id="delete_id"></span> 직원을 정말로 삭제하시겠습니까?
        <input type="hidden" id="del_id" name="id" value=""> 
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>
      </form>

    </div>
  </div>
</div>

<!--update모달-->
<div class="modal fade" id="update" tabindex="-1" role="dialog" aria-labelledby="updateLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="updateLabel">수정하기</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'employeeManage' %}?process=update&page={{this_page}}" method="POST">
      <div class="modal-body input-group">
        {% bootstrap_form employeeUpdateForm %}
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>

      </form>
    </div>
  </div>
</div>
{%endblock%}

UOS25/UOS25/mainapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-striped" style="margin-left:5px">
  <caption><h1 class="well">UOS25 가맹점 페이지입니다. 왼쪽 메뉴를 클릭해주세요.</h1></caption>
</table>

{% endblock %}

UOS25/UOS25/mainapp/templates/saleManage.html
{% extends 'base.html' %}
{% block content %}
  <div class="panel panel-default" style="margin-bottom:0px">
      <div class="panel-body" style="margin-left:50px">
        <h1>매출관리</h1>
      </div>
    </div>
    <table class="table table-striped" style="margin-left:5px">
      <thead>
        <tr>
          <th>해당 월</th>
          <th>총 매출액</th>
        </tr>
      </thead>
      <tbody>
        {% for record in records %}
          <tr>
            {% for value in record %}
              <td>{{ value }}</td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>

<!--추가 버튼 및 페이지 표시 -->
<nav>
  <div class="text-center">
    <ul class="pagination">
      <li>
          <span aria-hidden="true">-</span>
      </li>
      {% for page in pages %}
      {% if this_page == page %}
      <li class="active"><a href="?page={{page}}">{{page}}</a></li>
      {% else %}
      <li><a href="?page={{page}}">{{page}}</a></li>
      {% endif %}
      {% endfor %}
      <li>
          <span aria-hidden="true">-</span>
      </li>
    </ul>
  </div>


{%endblock%}

UOS25/UOS25/mainapp/templates/stockManage.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="panel panel-default" style="margin-bottom:0px">
  <div class="panel-body" style="margin-left:50px">
    <h1>재고 관리</h1>
  </div>
</div>
<table class="table table-striped" style="margin-left:5px">
  <thead>
    <tr>
      <th>상품</th>
      <th>전시 위치</th>
      <th>수량</th>
    </tr>
  </thead>
  <tbody>
    {% for stock in stocks %}
    <tr>
      <td>{{ stock.barcode }}</td>
      <td>{{ stock.get_display_location_code_display }}</td>
      <td>{{ stock.quantity }}</td>
      <td><button type="button" class="btn btn-success" data-toggle="modal" data-target="#update" 
        onclick="update_onclick({{ stock.id }}, {{ stock.barcode.barcode }}, {{ stock.display_location_code }}, {{ stock.quantity }} )">수정</button></td>
      <td><button type="button" class="btn btn-success" data-toggle="modal" data-target="#del" 
        onclick="delete_onclick({{ stock.id }}, '{{ stock.barcode }}_{{ stock.get_display_location_code_display }}')">삭제</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!--추가 버튼 및 페이지 표시 -->
<nav>
  <div class="text-center">
    <ul class="pagination">
      <li>
          <span aria-hidden="true">-</span>
      </li>
      {% for page in pages %}
      {% if this_page == page %}
      <li class="active"><a href="?page={{page}}">{{page}}</a></li>
      {% else %}
      <li><a href="?page={{page}}">{{page}}</a></li>
      {% endif %}
      {% endfor %}
      <li>
          <span aria-hidden="true">-</span>
      </li>
    </ul>
  </div>

  <!-- 추가 버튼 -->
  <div class="btn-group" role="group" style="margin-top:-100px;margin-left: 20px">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add">재고 추가</button>
  </div>

</nav>

<!--add모달-->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="addLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addLabel">재고 추가</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'stockManage' %}?process=register&page={{this_page}}" method="POST">
      <div class="modal-body input-group">
        {% bootstrap_form stockRegisterForm %}
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>
      </form>

    </div>
  </div>
</div>

<script type="text/javascript">
delete_onclick = function(id, name) {
  $("#delete_id").text(name);
  $("#del_id").val(id);
}
update_onclick = function(id, barcode, display_location_code, quantity) {
  $("#update_id").val(id);
  $("#update_barcode").val(barcode);
  $("#update_display_location_code").val(display_location_code);
  $("#update_quantity").val(quantity);
}
</script>

<!--del모달-->
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="delLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="delLabel">삭제하기</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'stockManage' %}?process=delete&page={{this_page}}" method="POST">
      <div class="modal-body">
        <span id="delete_id"></span> 의 재고를 정말로 삭제하시겠습니까?
        <input type="hidden" id="del_id" name="id" value=""> 
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>
      </form>

    </div>
  </div>
</div>

<!--update모달-->
<div class="modal fade" id="update" tabindex="-1" role="dialog" aria-labelledby="updateLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- 모달 창 제목 -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="updateLabel">수정하기</h4>
      </div>

      <!-- 모달 창 내용 -->
      <form action="{% url 'stockManage' %}?process=update&page={{this_page}}" method="POST">
      <div class="modal-body input-group">
        {% bootstrap_form stockUpdateForm %}
        {% csrf_token %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">확인</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
      </div>

      </form>
    </div>
  </div>
</div>
{%endblock%}